services:
  jellyfin-year-in-review:
    image: ${DOCKER_IMAGE:-jellyfin-year-in-review}
    build:
      dockerfile: ./Dockerfile
      args:
        - NEXT_PUBLIC_UMAMI_WEBSITE_ID=${NEXT_PUBLIC_UMAMI_WEBSITE_ID}
        - NEXT_PUBLIC_UMAMI_SRC=${NEXT_PUBLIC_UMAMI_SRC}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_JELLYFIN_URL=${NEXT_PUBLIC_JELLYFIN_URL}
        - NEXT_PUBLIC_JELLYFIN_SERVER_ID=${NEXT_PUBLIC_JELLYFIN_SERVER_ID}
        - NEXT_PUBLIC_SEER_URL=${NEXT_PUBLIC_SEER_URL}
    restart: "unless-stopped"
    env_file:
      - .env.local
    volumes:
      - ./db:/db:ro
    ports:
      - "3000:3000"
